/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convert;

import javax.swing.JOptionPane;

/**
 *
 * @author Santiago
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cjCOP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btConvertir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vlDolar = new javax.swing.JLabel();
        vlEuro = new javax.swing.JLabel();
        vlLibra = new javax.swing.JLabel();
        vlDolca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CONVERTIDOR DE MONEDA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 160, 50);

        cjCOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjCOPActionPerformed(evt);
            }
        });
        getContentPane().add(cjCOP);
        cjCOP.setBounds(210, 80, 150, 30);

        jLabel2.setText("Valor a convertir en COP:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 170, 60);

        btConvertir.setText("CONVERTIR");
        btConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(btConvertir);
        btConvertir.setBounds(400, 80, 110, 30);

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 330, 90, 23);

        jLabel3.setText("COP en Dólares");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 190, 120, 30);

        jLabel4.setText("COP en Euros");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 240, 90, 20);

        jLabel5.setText("COP en Libras");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 280, 110, 20);

        jLabel6.setText("COP en Dólares canadienses");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 320, 170, 20);

        vlDolar.setText("0");
        getContentPane().add(vlDolar);
        vlDolar.setBounds(230, 200, 130, 14);

        vlEuro.setText("0");
        getContentPane().add(vlEuro);
        vlEuro.setBounds(230, 240, 120, 14);

        vlLibra.setText("0");
        getContentPane().add(vlLibra);
        vlLibra.setBounds(230, 280, 110, 14);

        vlDolca.setText("0");
        getContentPane().add(vlDolca);
        vlDolca.setBounds(230, 320, 130, 14);

        setSize(new java.awt.Dimension(579, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjCOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjCOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjCOPActionPerformed

    private void btConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConvertirActionPerformed
        // TODO add your handling code here:
        this.convertir();
    }//GEN-LAST:event_btConvertirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.salir();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private void salir() {
        System.exit(0);
    }

    private void convertir() {
        //String vcop = cjCOP.getText();
        //int vncop = Integer.parseInt(vcop);
        //JOptionPane.showMessageDialog(this, vncop);
        this.dolares();
        this.euros();
        this.libras();
        this.canadiense();
    }

    private void dolares() {
        String vcop = cjCOP.getText();
        int vncop = Integer.parseInt(vcop);
        int vlrd = vncop * 3851;
        this.vlDolar.setText(""+vlrd);
        
    }
    private void euros() {
        String vcoop = cjCOP.getText();
        int vncoop = Integer.parseInt(vcoop);
        int vlre = vncoop * 4503;
        this.vlEuro.setText(""+vlre);
    }          

    private void libras() {
        String vcooop = cjCOP.getText();
        int vncooop = Integer.parseInt(vcooop);
        int vlrl = vncooop * 5290;
        this.vlLibra.setText(""+vlrl);
    }

    private void canadiense() {
        String vcoooop = cjCOP.getText();
        int vncoooop = Integer.parseInt(vcoooop);
        int vlrc = vncoooop * 3038;
        this.vlDolca.setText(""+vlrc);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConvertir;
    private javax.swing.JTextField cjCOP;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel vlDolar;
    private javax.swing.JLabel vlDolca;
    private javax.swing.JLabel vlEuro;
    private javax.swing.JLabel vlLibra;
    // End of variables declaration//GEN-END:variables
}
